version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  darkroom:
    container_name: darkroom
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/darkroom
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongodbdata:
